services:
  - type: web
    name: discount-server
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: SHOPIFY_TOKEN
        sync: false
      - key: PASS
        sync: false
